### ISSUE TITLE
IL Linker Error on Preview 9

### ISSUE THREAD

**Issue by endeffects** [BlazorExtensions/Notifications#11]
I'm receiving an IL Linker Error on Preview 9 for a Blazor Client Side Application

```
1>Type System.Reflection.Assembly has no fields to preserve
1>Type Mono.ValueTuple has no fields to preserve
1>Fatal error in IL Linker
1>
1>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task`1<System.Boolean> Blazor.Extensions.NotificationService::IsSupportedByBrowserAsync()' in assembly: 'Blazor.Extensions.Notifications.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime::InvokeAsync(System.String,System.Object[])
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>   at Mono.Linker.Steps.MarkStep.Process()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
```

**Comment by endeffects** [comment]
@vertonghenb @galvesribeiro Please update to .net core 3.0.0 final.

**Comment by vertonghenb** [comment]
@endeffects feel free to open a PR.

**Comment by endeffects** [comment]
so the project is no longer maintained? then i'm going to remove it.
