### ISSUE TITLE
Fatal error in Mono CIL Linker (blazor webassembly preview)

### ISSUE THREAD

**Issue by hultqvist** [BlazorExtensions/Notifications#15]
When using the extension in blazor webassembly preview it appears to have problem with linking.

.NET Core 3.1
Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1
Blazor.Extensions.Notifications version 0.1.3 (from NuGet)

```
1>------ Build started: Project: BlazorApp.Client, Configuration: Debug Any CPU ------
1>BlazorApp.Client -> C:\Users\...\BlazorApp\Client\bin\Debug\netstandard2.1\BlazorApp.Client.dll
1>Fatal error in Mono CIL Linker
1>C:\Users\...\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task`1<System.Boolean> Blazor.Extensions.NotificationService::IsSupportedByBrowserAsync()' in assembly: 'Blazor.Extensions.Notifications.dll'
1> ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime::InvokeAsync(System.String,System.Object[])
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>   at Mono.Linker.Steps.MarkStep.Process()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>C:\Users\...\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : ILLink failed with exit code -532462766.
1>Done building project "BlazorApp.Client.csproj" -- FAILED.
2>------ Build started: Project: BlazorApp.Server, Configuration: Debug Any CPU ------
2>BlazorApp.Server -> C:\Users\...\BlazorApp\Server\bin\Debug\netcoreapp3.1\BlazorApp.Server.dll
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

```

**Comment by vertonghenb** [comment]
FIxed by #17
